"""M00 — 公共契约包（规格版本 `rl.contract/1`，REFACTOR_SPEC §5）。

这些是**冻结接口**：任何模块（含子 agent 实现）只能依赖本包的 DTO，
不得跨模块导入对方的私有 repository / ORM 实体。
"""
from .common import (  # noqa: F401
    ArtifactRef,
    Budget,
    CallContext,
    CancelToken,
    Hash,
    AnchorId,
    AssetId,
    BlockId,
    Id,
    JobId,
    LegacyEvidenceId,
    MediaId,
    Origin,
    PageResult,
    PaperId,
    ProgressCallback,
    Point,
    Quad,
    Rect,
    RevisionId,
    Score,
    Scope,
    SourceRef,
    StatementId,
    Warning,
)
from .artifacts import (  # noqa: F401
    Asset,
    AssetKind,
    AssetRead,
    AssetWrite,
    ByteRange,
    ExtractedMedia,
    Media,
    MediaBuildResult,
    MediaKind,
    MediaLinkCandidate,
    MediaProvenance,
    MediaViewPolicy,
    TableCell,
)
from .documents import (  # noqa: F401
    Anchor,
    AnchorSegment,
    Block,
    BlockKind,
    CoordinateTransform,
    LegacyPaperMetadata,
    LegacyMethodStep,
    NavigationResult,
    NavigationTarget,
    Page,
    PageContent,
    PageLabelMapping,
    PageLabelOverride,
    PageResolution,
    PageSummary,
    PaperCreate,
    PaperRecord,
    ParsedMediaCandidate,
    ParseResult,
    ParseSummary,
    QuoteSpan,
    RawRef,
    Revision,
    RevisionKind,
    RevisionState,
    SourceDocument,
    SourceInput,
    SourceMetadata,
)
from .evidence import (  # noqa: F401
    ArtifactText,
    Binding,
    ClaimBuildResult,
    ClaimDraftBatch,
    ClaimRecord,
    CitationCandidate,
    EvidenceExport,
    EvidenceRecord,
    LegacyRef,
    MapArtifact,
    MapItem,
    MethodStepRecord,
    ResolutionReport,
    ReviewRecord,
    ReviewRequest,
    SectionRecord,
    StatementDraft,
    StatementSpan,
    StructureArtifact,
    ValidationReason,
    ValidationReport,
    VerifiedStatement,
)
from .ai import (  # noqa: F401
    ChatMessage,
    CompletionRequest,
    CompletionResult,
    EmbeddingBatch,
    ModelCapabilities,
    ModelSnapshot,
    SchemaRef,
    Usage,
)
from .retrieval import (  # noqa: F401
    Chunk,
    IndexResult,
    RetrievalHit,
    RetrievalRequest,
    RetrievalResult,
)
from .jobs import (  # noqa: F401
    JobEvent,
    JobEventData,
    JobLease,
    JobRecord,
    JobSpec,
    JobState,
    Stage,
    StageResult,
    StageStatus,
    SupervisorDecision,
    ToolArgs,
    ToolCall,
    ToolName,
    ToolResult,
)
from .evaluation import (  # noqa: F401
    EvaluationInput,
    EvaluationReport,
    GoldenAnchor,
    GoldenClaim,
    GoldenQuestion,
    GoldenSet,
    MetricEntry,
    MetricValue,
    NavigationCheck,
)
from .graph import (  # noqa: F401
    GraphArtifact,
    GraphEdgeRecord,
    GraphNodeRecord,
)
from .scene import (  # noqa: F401
    NarrationRecord,
    PresentationArtifact,
    SceneRecord,
    SubtitleCue,
)
from .qa import (  # noqa: F401
    AnswerRecord,
    AnswerMode,
    QAError,
    QACitation,
    QAFinal,
    QAMeta,
    QARequest,
    QASentence,
    QAStatus,
    QAStreamEvent,
    StreamEventType,
    StreamStage,
)

CONTRACT_VERSION = "rl.contract/1"

__all__ = ["CONTRACT_VERSION"]
