"""迁移辅助：以 ``checkfirst=True`` 建表，兼容「旧库已由 create_all 建过一部分」的现场。

设计取舍：迁移文件不追求与 ORM 定义 1:1 自动推导，而是显式声明 canonical 表，
这样 SQLite（需要 batch 模式）与 Postgres 的行为一致，且重复执行幂等。
"""
from __future__ import annotations

import sqlalchemy as sa

_md = sa.MetaData()


def _pk_str() -> sa.Column:
    return sa.Column("id", sa.String(36), primary_key=True)


def _pk_int() -> sa.Column:
    """旧表（legacy）主键：保留原有 int 身份（PaperId/JobId/LegacyEvidenceId 均为正整数）。"""
    return sa.Column("id", sa.Integer, primary_key=True, autoincrement=True)


def T(name: str, *cols, **kw) -> sa.Table:
    """构造（并缓存）表对象。"""
    if name in _md.tables:
        return _md.tables[name]
    return sa.Table(name, _md, *cols, **kw)


def has_table(name: str) -> bool:
    return name in _md.tables


# ------------------------------------------------------------------ 共享列

def _created() -> sa.Column:
    return sa.Column("created_at", sa.DateTime())


def _updated() -> sa.Column:
    return sa.Column("updated_at", sa.DateTime())


# ------------------------------------------------------------------ 表定义

#: 旧库 baseline（0001）
LEGACY_TABLES = {
    "papers": T(
        "papers",
        _pk_int(),
        sa.Column("slug", sa.String(64), unique=True, index=True),
        sa.Column("title", sa.String(512)),
        sa.Column("subtitle", sa.String(512), default=""),
        sa.Column("authors", sa.JSON(), default=list),
        sa.Column("year", sa.Integer(), default=2026),
        sa.Column("domain", sa.String(64), default="general"),
        sa.Column("abstract", sa.Text(), default=""),
        sa.Column("tags", sa.JSON(), default=list),
        sa.Column("pdf_url", sa.String(1024), default=""),
        sa.Column("source_mode", sa.String(16), default="demo"),
        sa.Column("status", sa.String(24), default="ready"),
        sa.Column("accent", sa.String(16), default="#6366F1"),
        sa.Column("map_summary", sa.JSON(), default=dict),
        sa.Column("method_steps", sa.JSON(), default=list),
        _created(),
    ),
    "paper_pages": T(
        "paper_pages",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("page_no", sa.Integer()),
        sa.Column("text", sa.Text(), default=""),
        sa.Column("blocks", sa.JSON(), default=list),
        sa.Column("region_map", sa.JSON(), default=dict),
    ),
    "sections": T(
        "sections",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("heading", sa.String(256)),
        sa.Column("kind", sa.String(32), default="body"),
        sa.Column("page", sa.Integer(), default=1),
        sa.Column("summary", sa.Text(), default=""),
        sa.Column("body", sa.Text(), default=""),
        sa.Column("key_points", sa.JSON(), default=list),
    ),
    "figures": T(
        "figures",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("fig_no", sa.Integer()),
        sa.Column("caption", sa.Text(), default=""),
        sa.Column("page", sa.Integer(), default=1),
        sa.Column("image_ref", sa.String(1024), default=""),
        sa.Column("glyph_svg", sa.Text(), default=""),
        sa.Column("image_b64", sa.Text(), default=""),
        sa.Column("importance", sa.String(16), default="medium"),
        sa.Column("description", sa.Text(), default=""),
    ),
    "tables": T(
        "tables",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("table_no", sa.Integer()),
        sa.Column("caption", sa.Text(), default=""),
        sa.Column("page", sa.Integer(), default=1),
        sa.Column("content", sa.JSON(), default=list),
        sa.Column("table_html", sa.Text(), default=""),
        sa.Column("key_finding", sa.Text(), default=""),
    ),
    "claims": T(
        "claims",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("claim_id", sa.String(32), index=True),
        sa.Column("statement", sa.Text()),
        sa.Column("type", sa.String(32), default="RESULT"),
        sa.Column("confidence", sa.Float(), default=0.9),
        sa.Column("status", sa.String(16), default="SUPPORTED"),
        sa.Column("rationale", sa.Text(), default=""),
        _created(),
    ),
    "evidences": T(
        "evidences",
        _pk_int(),
        sa.Column("claim_id", sa.Integer(), sa.ForeignKey("claims.id", ondelete="CASCADE")),
        sa.Column("page", sa.Integer(), default=1),
        sa.Column("region", sa.String(64), default=""),
        sa.Column("region_type", sa.String(16), default="text"),
        sa.Column("text", sa.Text(), default=""),
        sa.Column("quote", sa.Text(), default=""),
        sa.Column("confidence", sa.Float(), default=0.95),
    ),
    "graph_nodes": T(
        "graph_nodes",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("node_id", sa.String(32)),
        sa.Column("kind", sa.String(32)),
        sa.Column("label", sa.String(256)),
        sa.Column("props", sa.JSON(), default=dict),
    ),
    "graph_edges": T(
        "graph_edges",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("source", sa.String(32)),
        sa.Column("target", sa.String(32)),
        sa.Column("label", sa.String(128), default=""),
    ),
    "scenes": T(
        "scenes",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("order", sa.Integer()),
        sa.Column("title", sa.String(256)),
        sa.Column("kind", sa.String(32)),
        sa.Column("summary", sa.Text(), default=""),
        sa.Column("steps", sa.JSON(), default=list),
        sa.Column("evidence_refs", sa.JSON(), default=list),
        sa.Column("figure_refs", sa.JSON(), default=list),
        sa.Column("narration", sa.JSON(), default=dict),
    ),
    "narrations": T(
        "narrations",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("scene_id", sa.Integer(), default=0),
        sa.Column("script", sa.Text(), default=""),
        sa.Column("tts_text", sa.Text(), default=""),
        sa.Column("audio_url", sa.String(1024), default=""),
        sa.Column("subtitle", sa.Text(), default=""),
    ),
    "questions": T(
        "questions",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("q", sa.Text()),
        sa.Column("a", sa.Text()),
        sa.Column("evidence_refs", sa.JSON(), default=list),
        sa.Column("confidence", sa.String(16), default="High"),
        _created(),
    ),
    "evaluations": T(
        "evaluations",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("metrics", sa.JSON(), default=dict),
        sa.Column("overall_score", sa.Float(), default=0.0),
        sa.Column("computed_at", sa.DateTime()),
    ),
    "generation_jobs": T(
        "generation_jobs",
        _pk_int(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id", ondelete="CASCADE")),
        sa.Column("stage", sa.String(32), default="parse"),
        sa.Column("status", sa.String(24), default="pending"),
        sa.Column("payload", sa.JSON(), default=dict),
        _created(),
    ),
}

#: 0002 — 源文件 / 修订 / 资产 / 页块坐标
SOURCE_TABLES = {
    "source_documents": T(
        "source_documents",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("sha256", sa.String(64), index=True),
        sa.Column("asset_id", sa.String(36), default=""),
        sa.Column("byte_size", sa.Integer(), default=0),
        sa.Column("mime", sa.String(64), default="application/pdf"),
        sa.Column("page_count", sa.Integer(), default=0),
        sa.Column("source_url", sa.Text(), default=""),
        sa.Column("original_filename", sa.String(256), default=""),
        sa.Column("acquisition", sa.String(16), default="upload"),
        _created(),
        sa.UniqueConstraint("paper_id", "sha256", name="uq_source_paper_hash"),
    ),
    "revisions": T(
        "revisions",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("source_document_id", sa.String(36), nullable=True),
        sa.Column("kind", sa.String(16), default="source"),
        sa.Column("state", sa.String(16), default="staging"),
        sa.Column("parser_name", sa.String(64), default=""),
        sa.Column("parser_version", sa.String(64), default=""),
        sa.Column("normalizer_version", sa.String(64), default=""),
        sa.Column("prompt_version", sa.String(64), default=""),
        sa.Column("model_snapshot_id", sa.String(36), nullable=True),
        sa.Column("artifact_digest", sa.String(64), nullable=True),
        sa.Column("quality", sa.String(16), default="source_only"),
        sa.Column("warnings", sa.JSON(), default=list),
        _created(),
        _updated(),
        sa.Index("ix_revision_paper_state", "paper_id", "state"),
    ),
    "assets": T(
        "assets",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), nullable=True),
        sa.Column("sha256", sa.String(64), index=True),
        sa.Column("mime", sa.String(128), default="application/octet-stream"),
        sa.Column("byte_size", sa.Integer(), default=0),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(24), default="parser_raw"),
        sa.Column("rel_path", sa.String(512), default=""),
        _created(),
        sa.UniqueConstraint("paper_id", "sha256", "kind", name="uq_asset_paper_hash_kind"),
        sa.Index("ix_asset_revision", "revision_id"),
    ),
    "model_snapshots": T(
        "model_snapshots",
        _pk_str(),
        sa.Column("provider", sa.String(32), default="dashscope"),
        sa.Column("base_url", sa.String(256), default=""),
        sa.Column("chat_model", sa.String(128), default=""),
        sa.Column("embedding_model", sa.String(128), nullable=True),
        sa.Column("embedding_dimension", sa.Integer(), nullable=True),
        sa.Column("capability_version", sa.String(64), default="rl.capabilities/1"),
        sa.Column("temperature", sa.Float(), default=0.2),
        _created(),
        sa.UniqueConstraint("chat_model", "embedding_model", "capability_version",
                            name="uq_snapshot_identity"),
    ),
    "pages": T(
        "pages",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("pdf_page_index", sa.Integer()),
        sa.Column("page_label", sa.String(64), nullable=True),
        sa.Column("label_status", sa.String(16), default="unknown"),
        sa.Column("width_pt", sa.Float(), default=0.0),
        sa.Column("height_pt", sa.Float(), default=0.0),
        sa.Column("rotation", sa.Integer(), default=0),
        sa.Column("cropbox_pdf", sa.JSON(), default=list),
        sa.Column("text", sa.Text(), default=""),
        sa.Column("text_origin", sa.String(24), default="source_extraction"),
        sa.Column("preview_asset_id", sa.String(36), nullable=True),
        sa.Column("extraction_quality", sa.String(16), default="text"),
        sa.UniqueConstraint("revision_id", "pdf_page_index", name="uq_page_revision_index"),
        sa.Index("ix_page_scope", "paper_id", "revision_id"),
    ),
    "blocks": T(
        "blocks",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("page_id", sa.String(36), index=True),
        sa.Column("ordinal", sa.Integer(), default=0),
        sa.Column("kind", sa.String(24), default="paragraph"),
        sa.Column("text", sa.Text(), default=""),
        sa.Column("origin", sa.String(24), default="source_extraction"),
        sa.Column("anchor_id", sa.String(36), nullable=True),
        sa.Column("media_id", sa.String(36), nullable=True),
        sa.Column("section_path", sa.JSON(), default=list),
        sa.Column("raw_ref", sa.JSON(), default=dict),
        sa.Column("language", sa.String(16), default=""),
        sa.Column("content_hash", sa.String(64), nullable=True),
        sa.Index("ix_block_revision_page_ordinal", "revision_id", "page_id", "ordinal"),
    ),
    "anchors": T(
        "anchors",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("source_document_id", sa.String(36), default=""),
        sa.Column("precision", sa.String(16), default="page"),
        sa.Column("segments", sa.JSON(), default=list),
        sa.Column("transform", sa.JSON(), nullable=True),
        sa.Column("raw_ref", sa.JSON(), nullable=True),
        _created(),
        sa.Index("ix_anchor_scope", "paper_id", "revision_id"),
    ),
    "page_label_mappings": T(
        "page_label_mappings",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("page_label", sa.String(64)),
        sa.Column("pdf_page_index", sa.Integer()),
        sa.Column("method", sa.String(24), default="printed_ocr"),
        sa.Column("status", sa.String(16), default="candidate"),
        sa.Column("source_block_ids", sa.JSON(), default=list),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("review_id", sa.String(36), nullable=True),
        sa.Index("ix_label_scope_label", "paper_id", "revision_id", "page_label"),
    ),
    "media": T(
        "media",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("kind", sa.String(16), default="figure"),
        sa.Column("original_label", sa.String(64), nullable=True),
        sa.Column("legacy_no", sa.Integer(), nullable=True),
        sa.Column("caption", sa.Text(), default=""),
        sa.Column("caption_alt", sa.Text(), default=""),
        sa.Column("anchor_ids", sa.JSON(), default=list),
        sa.Column("original_asset_ids", sa.JSON(), default=list),
        sa.Column("thumbnail_asset_id", sa.String(36), nullable=True),
        sa.Column("extracted", sa.JSON(), nullable=True),
        sa.Column("provenance", sa.JSON(), default=dict),
        sa.Column("excluded", sa.Boolean(), default=False),
        sa.Column("exclusion_reason", sa.Text(), nullable=True),
        # legacy_no 按 kind 编号：图1/表1/公式1 可共存（详见 models/artifacts.py）。
        sa.UniqueConstraint(
            "revision_id", "kind", "legacy_no",
            name="uq_media_revision_kind_legacy_no",
        ),
        sa.Index("ix_media_scope_kind", "paper_id", "revision_id", "kind"),
    ),
    "artifact_blobs": T(
        "artifact_blobs",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("kind", sa.String(32)),
        sa.Column("payload", sa.JSON(), default=dict),
        sa.Column("digest", sa.String(64), nullable=True),
        _created(),
        _updated(),
        sa.UniqueConstraint("revision_id", "kind", name="uq_artifact_revision_kind"),
    ),
}

#: 0003 — 已验证产物
VERIFIED_TABLES = {
    "statements": T(
        "statements",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("claim_id", sa.String(32)),
        sa.Column("text", sa.Text(), default=""),
        sa.Column("kind", sa.String(16), default="fact"),
        sa.Column("citations", sa.JSON(), default=list),
        sa.Column("qualifiers", sa.JSON(), default=list),
        sa.Column("validation", sa.JSON(), nullable=True),
        sa.Column("evidence_ids", sa.JSON(), default=list),
        sa.Column("origin", sa.String(24), default="generated"),
        sa.Column("display_class", sa.String(24), default="unverified"),
        sa.Column("ordinal", sa.Integer(), default=0),
        sa.UniqueConstraint("revision_id", "claim_id", name="uq_statement_revision_claim"),
        sa.Index("ix_statement_scope", "paper_id", "revision_id"),
    ),
    "claim_records": T(
        "claim_records",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("claim_id", sa.String(32)),
        sa.Column("statement_id", sa.String(36)),
        sa.Column("type", sa.String(16), default="RESULT"),
        sa.Column("status", sa.String(16), default="unverified"),
        sa.Column("rationale", sa.Text(), default=""),
        sa.Column("evidence_ids", sa.JSON(), default=list),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("visibility", sa.String(16), default="exhibit"),
        sa.UniqueConstraint("revision_id", "claim_id", name="uq_claim_revision_claim"),
    ),
    "evidence_records": T(
        "evidence_records",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("claim_id", sa.String(32), default=""),
        sa.Column("source_document_id", sa.String(36), default=""),
        sa.Column("anchor_id", sa.String(36), default=""),
        sa.Column("source_page", sa.Integer(), default=1),
        sa.Column("source_region", sa.JSON(), default=list),
        sa.Column("source_text", sa.Text(), default=""),
        sa.Column("quote_spans", sa.JSON(), default=list),
        sa.Column("media_ids", sa.JSON(), default=list),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("confidence_method", sa.String(64), nullable=True),
        sa.Column("locator_status", sa.String(16), default="exact"),
        sa.Column("support_status", sa.String(16), default="unreviewed"),
        sa.Column("validation_id", sa.String(36), nullable=True),
        _created(),
        sa.Index("ix_evidence_revision_claim", "revision_id", "claim_id"),
    ),
    "validations": T(
        "validations",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("statement_id", sa.String(36), index=True),
        sa.Column("locator_valid", sa.Boolean(), default=False),
        sa.Column("quote_valid", sa.Boolean(), default=False),
        sa.Column("scope_valid", sa.Boolean(), default=False),
        sa.Column("semantic_status", sa.String(16), default="unreviewed"),
        sa.Column("numeric_status", sa.String(16), default="unreviewed"),
        sa.Column("qualifier_status", sa.String(16), default="unreviewed"),
        sa.Column("decision", sa.String(16), default="unverified"),
        sa.Column("evidence", sa.JSON(), default=list),
        sa.Column("reasons", sa.JSON(), default=list),
        sa.Column("assessor", sa.String(16), default="rule"),
        sa.Column("assessor_version", sa.String(64), default=""),
        sa.Column("confidence", sa.Float(), nullable=True),
        _created(),
        sa.Index("ix_validation_revision_statement", "revision_id", "statement_id"),
    ),
    "bindings": T(
        "bindings",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("from_kind", sa.String(24)),
        sa.Column("from_id", sa.String(64)),
        sa.Column("to_kind", sa.String(24)),
        sa.Column("to_id", sa.String(64)),
        sa.Column("relation", sa.String(16), default="supports"),
        sa.Column("method", sa.String(32), default="explicit_block_ref"),
        sa.Column("validation_id", sa.String(36), nullable=True),
        sa.Column("state", sa.String(16), default="candidate"),
        sa.Column("reason", sa.Text(), default=""),
        sa.Column("score", sa.Float(), nullable=True),
        _created(),
        sa.Index("ix_binding_revision_from", "revision_id", "from_kind", "from_id"),
        sa.Index("ix_binding_revision_to", "revision_id", "to_kind", "to_id"),
    ),
    "section_records": T(
        "section_records",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("heading", sa.Text(), default=""),
        sa.Column("kind", sa.String(32), default="body"),
        sa.Column("source_block_ids", sa.JSON(), default=list),
        sa.Column("anchor_ids", sa.JSON(), default=list),
        sa.Column("summary", sa.JSON(), default=dict),
        sa.Column("key_points", sa.JSON(), default=list),
        sa.Column("ordinal", sa.Integer(), default=0),
        sa.Index("ix_section_revision", "revision_id"),
    ),
    "method_steps": T(
        "method_steps",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("ordinal", sa.Integer(), default=0),
        sa.Column("label", sa.JSON(), default=dict),
        sa.Column("detail", sa.JSON(), default=dict),
        sa.Column("phase", sa.String(64), nullable=True),
        sa.Column("claim_ids", sa.JSON(), default=list),
        sa.Column("media_ids", sa.JSON(), default=list),
        sa.Column("binding_ids", sa.JSON(), default=list),
        sa.Index("ix_method_revision_ordinal", "revision_id", "ordinal"),
    ),
    "map_items": T(
        "map_items",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("kind", sa.String(16), default="problem"),
        sa.Column("text", sa.JSON(), default=dict),
        sa.Column("claim_ids", sa.JSON(), default=list),
        sa.Column("anchor_ids", sa.JSON(), default=list),
        sa.Column("ordinal", sa.Integer(), default=0),
        sa.Index("ix_map_revision_ordinal", "revision_id", "ordinal"),
    ),
    "answers": T(
        "answers",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("question", sa.Text(), default=""),
        sa.Column("text", sa.JSON(), default=dict),
        sa.Column("statements", sa.JSON(), default=list),
        sa.Column("evidence", sa.JSON(), default=list),
        sa.Column("grounded", sa.Boolean(), default=False),
        sa.Column("confidence", sa.String(8), default="Low"),
        sa.Column("note", sa.Text(), default=""),
        sa.Column("mode", sa.String(16), default="generated"),
        sa.Column("model_snapshot_id", sa.String(36), nullable=True),
        sa.Column("usage", sa.JSON(), default=dict),
        sa.Column("warnings", sa.JSON(), default=list),
        sa.Column("cache_key", sa.String(128), nullable=True),
        _created(),
        sa.Index("ix_answer_revision_cache", "revision_id", "cache_key"),
    ),
}

#: 0004 — 任务 / 检索 / 审计
OPS_TABLES = {
    "jobs": T(
        "jobs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), nullable=True),
        sa.Column("kind", sa.String(16), default="ingest"),
        sa.Column("state", sa.String(16), default="queued", index=True),
        sa.Column("stage", sa.String(24), default="acquire"),
        sa.Column("progress", sa.Float(), default=0.0),
        sa.Column("attempt", sa.Integer(), default=0),
        sa.Column("lease_owner", sa.String(64), nullable=True),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("fence", sa.Integer(), default=0),
        sa.Column("cancel_requested", sa.Boolean(), default=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("stage_results", sa.JSON(), default=list),
        sa.Column("spec", sa.JSON(), default=dict),
        sa.Column("model_snapshot", sa.JSON(), default=dict),
        sa.Column("budget", sa.JSON(), default=dict),
        sa.Column("idempotency_key", sa.String(128), nullable=True),
        _created(),
        _updated(),
        sa.UniqueConstraint("idempotency_key", name="uq_job_idempotency"),
        sa.Index("ix_job_state_lease", "state", "lease_until"),
    ),
    "job_events": T(
        "job_events",
        _pk_str(),
        sa.Column("job_id", sa.Integer(), sa.ForeignKey("jobs.id"), index=True),
        sa.Column("event_id", sa.Integer()),
        sa.Column("occurred_at", sa.DateTime()),
        sa.Column("type", sa.String(32), default="stage_started"),
        sa.Column("data", sa.JSON(), default=dict),
        sa.UniqueConstraint("job_id", "event_id", name="uq_job_event_seq"),
        sa.Index("ix_job_event_job", "job_id", "event_id"),
    ),
    "job_stage_keys": T(
        "job_stage_keys",
        _pk_str(),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("stage", sa.String(24)),
        sa.Column("input_digest", sa.String(64)),
        sa.Column("algorithm_version", sa.String(64)),
        sa.Column("status", sa.String(16), default="succeeded"),
        sa.Column("artifact_digest", sa.String(64), nullable=True),
        sa.Column("detail", sa.Text(), default=""),
        _created(),
        sa.UniqueConstraint("revision_id", "stage", "input_digest", "algorithm_version",
                            name="uq_stage_idempotency"),
    ),
    "chunks": T(
        "chunks",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("ordinal", sa.Integer(), default=0),
        sa.Column("text", sa.Text(), default=""),
        sa.Column("block_ids", sa.JSON(), default=list),
        sa.Column("anchor_ids", sa.JSON(), default=list),
        sa.Column("media_ids", sa.JSON(), default=list),
        sa.Column("section_path", sa.JSON(), default=list),
        sa.Column("content_hash", sa.String(64), default=""),
        sa.Column("token_estimate", sa.Integer(), default=0),
        sa.Column("embedding_space", sa.String(128), nullable=True),
        sa.UniqueConstraint("revision_id", "content_hash", name="uq_chunk_revision_hash"),
        sa.Index("ix_chunk_scope", "paper_id", "revision_id"),
    ),
    "chunk_vectors": T(
        "chunk_vectors",
        _pk_str(),
        sa.Column("chunk_id", sa.String(36), sa.ForeignKey("chunks.id"), index=True),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("space", sa.String(128)),
        sa.Column("dimension", sa.Integer(), default=0),
        sa.Column("vector", sa.JSON(), default=list),
        _created(),
        sa.UniqueConstraint("chunk_id", "space", name="uq_vector_chunk_space"),
        sa.Index("ix_vector_space", "space"),
    ),
    "reviews": T(
        "reviews",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("request", sa.JSON(), default=dict),
        sa.Column("target_kind", sa.String(24), default=""),
        sa.Column("target_id", sa.String(64), default=""),
        sa.Column("decision", sa.String(24), default="confirm"),
        sa.Column("reason", sa.Text(), default=""),
        sa.Column("reason_digest", sa.String(64), default=""),
        sa.Column("expected_validation_id", sa.String(36), nullable=True),
        sa.Column("reviewer", sa.String(64), default="anonymous"),
        _created(),
        sa.Column("applied_revision_id", sa.String(36), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.UniqueConstraint("revision_id", "target_kind", "target_id", "decision",
                            "reason_digest", name="uq_review_dedup"),
        sa.Index("ix_review_scope", "paper_id", "revision_id"),
    ),
    "audit_log": T(
        "audit_log",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), nullable=True, index=True),
        sa.Column("revision_id", sa.String(36), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(48), default=""),
        sa.Column("actor", sa.String(64), default="system"),
        sa.Column("payload", sa.JSON(), default=dict),
        sa.Column("occurred_at", sa.DateTime()),
        sa.Index("ix_audit_scope", "paper_id", "revision_id", "kind"),
    ),
    "evaluation_reports": T(
        "evaluation_reports",
        _pk_str(),
        sa.Column("paper_id", sa.Integer(), sa.ForeignKey("papers.id"), index=True),
        sa.Column("revision_id", sa.String(36), index=True),
        sa.Column("version", sa.String(32), default="rl.eval/1"),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("metrics", sa.JSON(), default=list),
        sa.Column("golden_id", sa.String(64), nullable=True),
        sa.Column("warnings", sa.JSON(), default=list),
        sa.Column("computed_at", sa.DateTime()),
        sa.Index("ix_eval_scope", "paper_id", "revision_id"),
    ),
    "golden_sets": T(
        "golden_sets",
        _pk_str(),
        sa.Column("golden_id", sa.String(64), index=True),
        sa.Column("version", sa.String(64)),
        sa.Column("payload", sa.JSON(), default=dict),
        sa.Column("is_tuning", sa.Boolean(), default=False),
        _created(),
        sa.UniqueConstraint("golden_id", "version", name="uq_golden_id_version"),
    ),
}


def ensure_tables(tables: dict, bind) -> None:
    """按依赖顺序建表（checkfirst=True，幂等）。"""
    for name, table in tables.items():
        table.create(bind, checkfirst=True)
        for idx in table.indexes:
            try:
                idx.create(bind, checkfirst=True)
            except Exception:  # noqa: BLE001  索引已存在/方言差异不阻断
                pass


def ensure_columns(bind, table: str, columns: dict[str, sa.types.TypeEngine]) -> None:
    """为已存在表补列（SQLite / Postgres 通用，忽略重复）。"""
    insp = sa.inspect(bind)
    if table not in insp.get_table_names():
        return
    existing = {c["name"] for c in insp.get_columns(table)}
    for name, type_ in columns.items():
        if name in existing:
            continue
        try:
            bind.execute(sa.text(f'ALTER TABLE "{table}" ADD COLUMN "{name}" {type_.compile(bind.dialect)}'))
        except Exception:  # noqa: BLE001  并发/方言差异
            pass
